### ISSUE TITLE
Contour levels for annual vs seasonal plots

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#41]
Some variables in ACME Diags use different contour levels for annual and seasonal lat-lon map plots. Somehow, this does not seem to be working when calling ACME Diags from processflow.

This is what I get from stand-alobe ACME Diags:

![ceres_ebaf_toa_v4 0-swcf-ann-global](https://user-images.githubusercontent.com/15743046/30876485-a6152a38-a2ab-11e7-8e98-0f6d46522141.png)

This is what I get from ACME Diags called by processflow. The contour levels are not the correct default.

![ceres_ebaf_toa_v4 0-swcf-ann-global](https://user-images.githubusercontent.com/15743046/30876533-c5f1de82-a2ab-11e7-9a08-7afae431a9ba.png)

**Comment by golaz** [comment]
The bad 500 mb geopotential plot is also there with processflow

![era-interim-z3-500-ann-global](https://user-images.githubusercontent.com/15743046/30877603-1044f476-a2af-11e7-8a3c-e5163445a313.png)

**Comment by sterlingbaldwin** [comment]
Im only passing a couple parameters, @zshaheen you have any idea what could be causing this?
```
reference_data_path = '/p/cscratch/acme/data/obs_for_acme_diags/'
test_data_path = '/p/cscratch/acme/baldwin32/test_10/output/tmp/acme_diags/year_set_1/'
test_name = 'case_scripts'
seasons = ['DJF', 'MAM', 'JJA', 'SON', 'ANN']
backend = 'mpl'
sets = [5]
results_dir = '/p/cscratch/acme/baldwin32/test_10/output/acme_diags/0001-0005/'
multiprocessing = True
num_workers = 32
```

**Comment by zshaheen** [comment]
@golaz @sterlingbaldwin 

I think both of you have an older version of `acme_diags`.
You can either fix this via Anaconda or from source.

**Anaconda**
- Remove the installation: `conda remove acme_diags`
- Install the latest `acme_diags` again:
  - `conda clean --all`
  - `conda install acme_diags -c acme -c conda-forge -c uvcdat`

**From source**
- Remove the installation on your env, look at my last comment [here](https://github.com/ACME-Climate/acme_diags/issues/87). 
- Clone the repo and install from master

That should fix the issues for both of you.

**Comment by golaz** [comment]
Thanks, @zshaheen. I'm pretty sure not invoking `conda clean --all` is the mistake I made. @sterlingbaldwin is currently working on other fixes; I'll redo a clean test once there is an updated version of processflow.

**Comment by golaz** [comment]
Reopening. This is just not working for me. Even after a clean re-installation of processflow following @zshaheen suggestion, I'm still not getting the same plots as when I do a clean installation of stand-aonlone ACME diags.

**Comment by sterlingbaldwin** [comment]
@golaz I'll work with @zshaheen and see if we can find the problem.

**Comment by golaz** [comment]
Note that this is still an issue with the latest version of processflow (1.0.0-rc5). It's probably a bug in E3SM Diags that manifest itself only when installed in the processflow environment.

@zshaheen : can you resolve this once for all?

**Comment by zshaheen** [comment]
@sterlingbaldwin Well, it seems like the processflow env might not have the correct version of `acme_diags`. Maybe both you and @golaz can run `python -c 'import acme_diags; print(acme_diags.__version__)'`  in a processflow env and make sure that `acme_diags` is a version that has this error fixed.

```
(acme_diags_env_old) shaheen2@aims4:~$ python -c 'import acme_diags; print(acme_diags.__version__)'
v1.2.1
```

@golaz You can use this to compare the version in the processflow env with that from a working acme_diags env.

**Comment by golaz** [comment]
I think the three of you (@zshaheen, @sterlingbaldwin and @chengzhuzhang) should be able to figure this out on you own. I just followed the instructions to install the processflow environment.

**Comment by zshaheen** [comment]
@sterlingbaldwin Then can you run this on an env in which the processflow creates the incorrect plots?

**Comment by golaz** [comment]
@zshaheen : I believe that @sterlingbaldwin has already verified that the problem exists as well when running E3SM Diags in stand-alone mode using the processflow environment. I'll let @sterlingbaldwin summarize the tests he has already performed.
My hypothesis is that there is a bug in E3SM Diags or CDP that for some reasons causes the wrong contour levels to be passed to the plotting routine when those levels are different between ANN and seasonal plots. 
It might be tedious, but it shouldn't be too hard for you to trace the source of the problem.

**Comment by sterlingbaldwin** [comment]
The processflow is still using version 1.1.0, I'll switch over to v1.2.1 and see if it fixes the problem.

**Comment by chengzhuzhang** [comment]
Hi @sterlingbaldwin, if you can summarize the tests have be done.  I will try if i can reproduce the issue when running E3SM Diags in stand-alone mode using the processflow environment. Thanks!

**Comment by golaz** [comment]
I'm running 1.1.0 on NERSC and I don't see the problem.

**Comment by zshaheen** [comment]
@golaz We had an issue sometime ago where we forgot to update `acme_diags.__version__` to whatever version we have when we released it. So there may be some confusion in that.

You're now running `1.1.0` which was released on December 14, 2017 and this problem was first reported on September 26, 2017. Since you don't see the problem, does this mean we're all good now?

**Comment by golaz** [comment]
No, I see the problem when running E3SM Diags with the processflow (in an environment created a few days ago).

**Comment by zshaheen** [comment]
This is an email I wrote to everyone regarding this issue.

## Temporary solution for the Processflow
In the run.cfg script you use Sterling, the one where the parameters of which get passed into acme_diags, remove the following:
```
seasons = ['DJF', 'MAM', 'JJA', 'SON', 'ANN']
```
See below as to why it breaks.
 
## Why it breaks
Chris, in [this comment](https://github.com/ACME-Climate/acme_processflow/issues/41#issue-260719818), you gave one example of plots that break in the acme_processflow, but not when running acme_diags independently.
Below are the parameters for the SWCF variable:
```cfg
[#]
sets = ["lat_lon"]
case_id = "CERES-EBAF-TOA-v2.8"
variables = ["SWCF"]
ref_name = "ceres_ebaf_toa_v2.8"
reference_name = "CERES-EBAF Jan 2000-Dec 2015"
seasons = ["ANN"]
regions = ["global"]
contour_levels = [-120, -110, -100, -90, -80, -70, -60, -50, -40, -30, -20, -10, 0]
diff_levels = [-60, -50, -40, -30, -20, -10, -5, 5, 10, 20, 30, 40, 50, 60]
 
[#]
sets = ["lat_lon"]
case_id = "CERES-EBAF-TOA-v2.8"
variables = ["SWCF"]
ref_name = "ceres_ebaf_toa_v2.8"
reference_name = "CERES-EBAF Jan 2000-Dec 2015"
seasons = ["DJF", "MAM", "JJA", "SON"]
regions = ["global"]
contour_levels = [-180, -160, -140, -120, -100, -80, -60, -40, -20,  0]
diff_levels = [-60, -50, -40, -30, -20, -10, -5, 5, 10, 20, 30, 40, 50, 60]
```

**When you run acme_diags independently, you probably didn’t put `seasons=['DJF', 'MAM', 'JJA', 'SON', 'ANN']` in the `*py` file (as in `acme_diags_driver.py -p something.py`)**
**So the seasons parameter wasn’t overwritten, so the plots with the correct contour levels were created.**

---

Now when you do put `seasons = ['DJF', 'MAM', 'JJA', 'SON', 'ANN']` in the `*py` file, **as the processflow does**, you’ll get the following parameters for SWCF and others:
```cfg
[#]
sets = ["lat_lon"]
case_id = "CERES-EBAF-TOA-v2.8"
variables = ["SWCF"]
ref_name = "ceres_ebaf_toa_v2.8"
reference_name = "CERES-EBAF Jan 2000-Dec 2015"
seasons = ["DJF", "MAM", "JJA", "SON", "ANN"]  # This is bad
regions = ["global"]
contour_levels = [-120, -110, -100, -90, -80, -70, -60, -50, -40, -30, -20, -10, 0]
diff_levels = [-60, -50, -40, -30, -20, -10, -5, 5, 10, 20, 30, 40, 50, 60]
 
[#]
sets = ["lat_lon"]
case_id = "CERES-EBAF-TOA-v2.8"
variables = ["SWCF"]
ref_name = "ceres_ebaf_toa_v2.8"
reference_name = "CERES-EBAF Jan 2000-Dec 2015"
seasons = ["DJF", "MAM", "JJA", "SON", "ANN"]  # This is also bad
regions = ["global"]
contour_levels = [-180, -160, -140, -120, -100, -80, -60, -40, -20,  0]
diff_levels = [-60, -50, -40, -30, -20, -10, -5, 5, 10, 20, 30, 40, 50, 60]
```

**You can see now that this is why you get the wrong ANN plot with the wrong contour levels, it’s created from the second set of parameters.
Even when you use multiprocessing, the order is even more random. Whatever parameter is done last, that’s the one that’s saved by overwriting the previous one.**

## Solution
We don’t know :(
There should be some way to couple sets of parameters, like the two aforementioned sets of diagnostics.
When the season parameter needs to be overwritten, it can’t do what it currently does.
 
## An Aside: The other bad plot
In [this comment](https://github.com/ACME-Climate/acme_processflow/issues/41#issuecomment-332294433) on the same issue, on September 26, 2017, you said that Z3 gave a bad plot.
On NERSC, the data was updated in November with Jerry’s fix for the Z3 data.
Hence, we’re pretty sure that that error will no longer be there.
This is something that was wrong with both acme_processflow and acme_diags. It’s not related to the above issue.

## What now?
Sterling can implement the quick fix, while Jill and I try to find a permanent solution.

**Comment by zshaheen** [comment]
Track the (eventual) solution to this issue here: [ACME-Climate/acme_diags/132](https://github.com/ACME-Climate/acme_diags/issues/132).

**Comment by sterlingbaldwin** [comment]
Im making the changes to processflow, should have a new build by EOD if all the tests pass.

**Comment by sterlingbaldwin** [comment]
This issue should be fixed in the latest master build. [See here for test output](https://acme-viewer.llnl.gov/baldwin32/20171122.beta3rc10_1850.ne30_oECv3_ICG.edison/e3sm-diags/0001-0005/viewer/latitude-longitude/ceres-ebaf-toa-v28/swcf-global-ceres_ebaf_toa_v28/ann.html)

**Comment by sterlingbaldwin** [comment]
It looks like the [500 mb geopotential](https://acme-viewer.llnl.gov/baldwin32/20171122.beta3rc10_1850.ne30_oECv3_ICG.edison/e3sm-diags/0001-0005/viewer/latitude-longitude/era-interim/z3-500mb-global-era-interim/ann.html) are also correct.
